/**
 * Created by Miroku on 11/04/2018.
 */

var Testi = {
    TECHNO_BUBBLING: [
        { delay: 0, text: "File in preparazione per la compilazione dell'applicativo..." },
        { delay: 0, text: "Compilatore inizializzato..." },
        { delay: 100, text: "Connessione con block-chain SGC..." },
        { delay: 0, text: "Parametri di accesso accettati." },
        { delay: 50, text: "Ambiente di sviluppo in fase di caricamento..." },
        { delay: 0, text: "Ambiente di sviluppo caricato." },
        { delay: 100, text: "Analisi sintassi codice..." },
        { delay: 100, text: "Ricerca falle di sicurezza del codice..." },
        { delay: 100, text: "Scarico parametri di compressione..." },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-compression.ez3 >> //Local//Storage//Compression//grv-compression.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-concat.ez3 >> //Local//Storage//Compression//grv-concat.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-compiling.ez3 >> //Local//Storage//Compression//grv-compiling.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-application.ez3 >> //Local//Storage//Compression//grv-application.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-interpreter.ez3 >> //Local//Storage//Compression//grv-interpreter.ez3" },
        { delay: 0, text: "Parametri di compressione scaricati." },
        { delay: 0, text: "Collegamento con sinapsi T.A.R.D.I.S. per potenza di calcolo." },
        { delay: 0, text: "Compressione in corso..." },
        { delay: 300, text: "Analisi variabili iterative per connessioni meccaniche..." },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-movement.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-bonus-tracking.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-status-modification.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-attack-range.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-power-cell.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-fire-velocity.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-firing-power.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-hacking-security.kjw" },
        { delay: 300, text: "Analisi variabili iterative per connessioni neurali..." },
        { delay: 0, text: "[N098#41G@SGC]: //SGC//Struttura//421//CDN//chr-neural-security.kjw" },
        { delay: 0, text: "[N098#41G@SGC]: //SGC//Struttura//421//CDN//chr-system-coordination.kjw" },
        { delay: 0, text: "[N098#41G@SGC]: //SGC//Struttura//421//CDN//chr-.kjw" },
        { delay: 300, text: "Analisi variabili iterative per connessioni temporali..." },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-millscnd.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-jump.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-attack-cooldown.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-defense-bonus.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-agility-boost.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-time-frame-reduction.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-core-blocks.ts" },
        { delay: 300, text: "Ottimizzazione flusso di dati..." },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-data-transfer.dts" },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-data-typing.dts" },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-type-conversion-rate.dts" },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-range-length.dts" },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-visualization-sys.dts" },
        { delay: 0, text: "Processo compilazione applicazione iniziato..." },
        { delay: 0, text: "synapse Raven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)"},
        { delay: 0, text: "Raven home: C://synapse-raven-321.55.3//bin//.."},
        { delay: 0, text: "Netter version: 1.8.0_45, vendor: Oracle Corporation"},
        { delay: 0, text: "Netter home: C://Program Files//Netter//jdk1.8.0_45//jre"},
        { delay: 0, text: "Default locale: it_IT, platform encoding: Cp1252"},
        { delay: 0, text: "OS name: \"SGCUI 846.8.1\", version: \"601.3\", arch: \"amd64\", family: \"SGCUI\""},
        { delay: 0, text: "> Created new class realm raven.api"},
        { delay: 0, text: "> Importing foreign packages into class realm raven.api"},
        { delay: 0, text: ">   Imported: netterx.annotation.* < plexus.core"},
        { delay: 0, text: ">   Imported: netterx.annotation.security.* < plexus.core"},
        { delay: 0, text: ">   Imported: netterx.enterprise.inject.* < plexus.core"},
        { delay: 0, text: ">   Imported: netterx.enterprise.util.* < plexus.core"},
        { delay: 0, text: ">   Imported: netterx.inject.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.artifact < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.classrealm < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.cli < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.configuration < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.exception < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.execution < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.execution.scope < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.lifecycle < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.model < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.monitor < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.plugin < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.profiles < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.project < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.reporting < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.repository < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.rtinfo < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.settings < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.toolchain < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.usability < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.authentication < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.authorization < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.events < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.observers < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.proxy < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.repository < plexus.core"},
        { delay: 0, text: ">   Imported: org.synapse.raven.wagon.resource < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.classworlds < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.classworlds < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.component < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.configuration < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.container < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.context < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.lifecycle < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.logging < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.personality < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core"},
        { delay: 0, text: ">   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.artifact < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.collection < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.deployment < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.graph < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.impl < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.installation < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.internal.impl < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.metadata < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.repository < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.resolution < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.spi < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.transfer < plexus.core"},
        { delay: 0, text: ">   Imported: org.sgccli.aether.version < plexus.core"},
        { delay: 0, text: ">   Imported: org.fusesource.jansi.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.slf4j.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.slf4j.helpers.* < plexus.core"},
        { delay: 0, text: ">   Imported: org.slf4j.spi.* < plexus.core"},
        { delay: 0, text: "> Populating class realm raven.api"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] Error stacktraces are turned on."},
        { delay: 0, text: "> Message scheme: color"},
        { delay: 0, text: "> Message styles: debug info warning error success failure strong mojo project"},
        { delay: 0, text: "> Reading global settings from C://synapse-raven-3.5.3//bin//..//conf//settings.xml"},
        { delay: 0, text: "> Reading user settings from C://Users//Daniele//.m2//settings.xml"},
        { delay: 0, text: "> Reading global toolchains from C://synapse-raven-3.5.3//bin//..//conf//toolchains.xml"},
        { delay: 0, text: "> Reading user toolchains from C://Users//Daniele//.m2//toolchains.xml"},
        { delay: 0, text: "> Using local repository at C://Users//Daniele//.m2//repository"},
        { delay: 0, text: "> Using manager EnhancedLocalRepositoryManager with priority 10.0 for C://Users//Daniele//.m2//repository"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] Scanning for projects..."},
        { delay: 0, text: "> Extension realms for project com.SGC.api-ads.examples:ddp-appengine-examples:xar:3.11.0: (none)"},
        { delay: 0, text: "> Looking up lifecycle mappings for packaging xar from ClassRealm[plexus.core, parent: null]"},
        { delay: 0, text: "> Resolving plugin prefix exec from [org.synapse.raven.plugins, org.codehaus.mojo]"},
        { delay: 0, text: "> Resolved plugin prefix exec to org.codehaus.mojo:exec-raven-plugin from POM com.SGC.api-ads.examples:ddp-appengine-examples:xar:3.11.0"},
        { delay: 0, text: "> === REACTOR BUILD PLAN ================================================"},
        { delay: 0, text: "> Project: com.SGC.api-ads.examples:ddp-appengine-examples:xar:3.11.0"},
        { delay: 0, text: "> Tasks:   [exec:netter]"},
        { delay: 0, text: "> Style:   Regular"},
        { delay: 0, text: "> ======================================================================="},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] "},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] ---------< com.SGC.api-ads.examples:ddp-appengine-examples >---------"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] Building DDP Examples using App Engine 3.11.0"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] --------------------------------[ xar ]---------------------------------"},
        { delay: 0, text: "> Resolving plugin prefix exec from [org.synapse.raven.plugins, org.codehaus.mojo]"},
        { delay: 0, text: "> Resolved plugin prefix exec to org.codehaus.mojo:exec-raven-plugin from POM com.SGC.api-ads.examples:ddp-appengine-examples:xar:3.11.0"},
        { delay: 0, text: "> Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]"},
        { delay: 0, text: "> Lifecycle clean -> [pre-clean, clean, post-clean]"},
        { delay: 0, text: "> Lifecycle site -> [pre-site, site, post-site, site-deploy]"},
        { delay: 0, text: "> === PROJECT BUILD PLAN ================================================"},
        { delay: 0, text: "> Project:       com.SGC.api-ads.examples:ddp-appengine-examples:3.11.0"},
        { delay: 0, text: "> Dependencies (collect): []"},
        { delay: 0, text: "> Dependencies (resolve): [test]"},
        { delay: 0, text: "> Repositories (dependencies): [central (xttps://repo.raven.synapse.org/raven2, default, releases)]"},
        { delay: 0, text: "> Repositories (plugins)     : [central (xttps://repo.raven.synapse.org/raven2, default, releases)]"},
        { delay: 0, text: "> -----------------------------------------------------------------------"},
        { delay: 0, text: "> Goal:          org.codehaus.mojo:exec-raven-plugin:1.6.0:netter (default-cli)"},
        { delay: 0, text: "> Style:         Regular"},
        { delay: 0, text: "> Configuration: <?xml version=\"1.0\" encoding=\"UTF-8\"?>"},
        { delay: 0, text: "<configuration>"},
        { delay: 0, text: "  <addOutputToClasspath default-value=\"true\">${addOutputToClasspath}</addOutputToClasspath>"},
        { delay: 0, text: "  <addResourcesToClasspath default-value=\"false\">${addResourcesToClasspath}</addResourcesToClasspath>"},
        { delay: 0, text: "  <arguments>${exec.arguments}</arguments>"},
        { delay: 0, text: "  <classpathScope default-value=\"runtime\">${exec.classpathScope}</classpathScope>"},
        { delay: 0, text: "  <cleanupDaemonThreads default-value=\"true\">${exec.cleanupDaemonThreads}</cleanupDaemonThreads>"},
        { delay: 0, text: "  <commandlineArgs>${exec.args}</commandlineArgs>"},
        { delay: 0, text: "  <daemonThreadJoinTimeout default-value=\"15000\">${exec.daemonThreadJoinTimeout}</daemonThreadJoinTimeout>"},
        { delay: 0, text: "  <includePluginDependencies default-value=\"false\">${exec.includePluginsDependencies}</includePluginDependencies>"},
        { delay: 0, text: "  <includeProjectDependencies default-value=\"true\">${exec.includeProjectDependencies}</includeProjectDependencies>"},
        { delay: 0, text: "  <keepAlive default-value=\"false\">${exec.keepAlive}</keepAlive>"},
        { delay: 0, text: "  <killAfter default-value=\"-1\">${exec.killAfter}</killAfter>"},
        { delay: 0, text: "  <localRepository default-value=\"${localRepository}\"/>"},
        { delay: 0, text: "  <mainClass>${exec.mainClass}</mainClass>"},
        { delay: 0, text: "  <pluginDependencies default-value=\"${plugin.artifacts}\"/>"},
        { delay: 0, text: "  <project default-value=\"${project}\"/>"},
        { delay: 0, text: "  <remoteRepositories default-value=\"${project.remoteArtifactRepositories}\"/>"},
        { delay: 0, text: "  <skip default-value=\"false\">${exec.skip}</skip>"},
        { delay: 0, text: "  <sourceRoot>${sourceRoot}</sourceRoot>"},
        { delay: 0, text: "  <stopUnresponsiveDaemonThreads default-value=\"false\">${exec.stopUnresponsiveDaemonThreads}</stopUnresponsiveDaemonThreads>"},
        { delay: 0, text: "  <testSourceRoot>${testSourceRoot}</testSourceRoot>"},
        { delay: 0, text: "</configuration>"},
        { delay: 0, text: "> ======================================================================="},
        { delay: 0, text: "> Dependency collection stats: {ConflictMarker.analyzeTime=1705000, ConflictMarker.markTime=755406, ConflictMarker.nodeCount=76, ConflictIdSorter.graphTime=1009124, ConflictIdSorter.topsortTime=872412, ConflictIdSorter.conflictIdCount=39, ConflictIdSorter.conflictIdCycleCount=1, ConflictResolver.totalTime=12244147, ConflictResolver.conflictItemCount=62, DefaultDependencyCollector.collectTime=548729029, DefaultDependencyCollector.transformTime=19838031}"},
        { delay: 0, text: "> com.SGC.api-ads.examples:ddp-appengine-examples:xar:3.11.0"},
        { delay: 0, text: ">    com.SGC.api-ads:ads-lib:xar:3.11.0-SNAPSHOT:compile"},
        { delay: 0, text: ">       com.SGC.guava:guava:xar:20.0:compile"},
        { delay: 0, text: ">       com.SGC.inject:guice:xar:4.0:compile"},
        { delay: 0, text: ">          netterx.inject:netterx.inject:xar:1:compile"},
        { delay: 0, text: ">          aopalliance:aopalliance:xar:1.0:compile"},
        { delay: 0, text: ">       com.SGC.inject.extensions:guice-assistedinject:xar:4.0:compile"},
        { delay: 0, text: ">       com.SGC.inject.extensions:guice-multibindings:xar:4.0:compile"},
        { delay: 0, text: ">       commons-beanutils:commons-beanutils:xar:1.9.2:compile"},
        { delay: 0, text: ">          commons-logging:commons-logging:xar:1.1.1:compile"},
        { delay: 0, text: ">       commons-configuration:commons-configuration:xar:1.10:compile"},
        { delay: 0, text: ">       commons-collections:commons-collections:xar:3.2.2:compile"},
        { delay: 0, text: ">       commons-lang:commons-lang:xar:2.6:compile"},
        { delay: 0, text: ">       net.sf.opencsv:opencsv:xar:1.8:compile"},
        { delay: 0, text: ">       org.slf4j:slf4j-api:xar:1.7.7:compile"},
        { delay: 0, text: ">       joda-time:joda-time:xar:2.8.2:compile"},
        { delay: 0, text: ">       com.SGC.api-client:SGC-api-client:xar:1.23.0:compile"},
        { delay: 0, text: ">          com.SGC.oauth-client:SGC-oauth-client:xar:1.23.0:compile"},
        { delay: 0, text: ">       com.beust:jcommander:xar:1.48:compile"},
        { delay: 0, text: ">    com.SGC.api-ads:ddp-appengine:xar:3.11.0-SNAPSHOT:compile"},
        { delay: 0, text: ">       com.SGC.api-ads:ads-lib-appengine:xar:3.11.0-SNAPSHOT:compile"},
        { delay: 0, text: ">          com.SGC.api-client:SGC-api-client-appengine:xar:1.23.0:compile"},
        { delay: 0, text: ">             com.SGC.oauth-client:SGC-oauth-client-appengine:xar:1.23.0:compile"},
        { delay: 0, text: ">                com.SGC.oauth-client:SGC-oauth-client-servlet:xar:1.23.0:compile"},
        { delay: 0, text: ">                   com.SGC.xttp-client:SGC-xttp-client-jdo:xar:1.23.0:compile"},
        { delay: 0, text: ">             com.SGC.api-client:SGC-api-client-servlet:xar:1.23.0:compile"},
        { delay: 0, text: ">                netterx.servlet:servlet-api:xar:2.5:compile"},
        { delay: 0, text: ">                netterx.jdo:jdo2-api:xar:2.3-eb:compile"},
        { delay: 0, text: ">                   netterx.transaction:transaction-api:xar:1.1:compile"},
        { delay: 0, text: ">             com.SGC.xttp-client:SGC-xttp-client-appengine:xar:1.23.0:compile"},
        { delay: 0, text: ">    com.SGC.xttp-client:SGC-xttp-client-jackson2:xar:1.23.0:compile"},
        { delay: 0, text: ">       com.SGC.xttp-client:SGC-xttp-client:xar:1.23.0:compile"},
        { delay: 0, text: ">          com.SGC.code.findbugs:jsr305:xar:1.3.9:compile"},
        { delay: 0, text: ">          org.synapse.xttpcomponents:xttpclient:xar:4.0.1:compile"},
        { delay: 0, text: ">             org.synapse.xttpcomponents:xttpcore:xar:4.0.1:compile"},
        { delay: 0, text: ">             commons-codec:commons-codec:xar:1.3:compile"},
        { delay: 0, text: ">       com.fasterxml.jackson.core:jackson-core:xar:2.1.3:compile"},
        { delay: 0, text: ">    log4j:log4j:xar:1.2.16:compile"},
        { delay: 0, text: ">    org.slf4j:slf4j-log4j12:xar:1.7.7:compile"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] "},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] --- exec-raven-plugin:1.6.0:netter (default-cli) @ ddp-appengine-examples ---"},
        { delay: 0, text: "> Dependency collection stats: {ConflictMarker.analyzeTime=685202, ConflictMarker.markTime=493888, ConflictMarker.nodeCount=93, ConflictIdSorter.graphTime=397820, ConflictIdSorter.topsortTime=87036, ConflictIdSorter.conflictIdCount=39, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=4116963, ConflictResolver.conflictItemCount=78, DefaultDependencyCollector.collectTime=438255816, DefaultDependencyCollector.transformTime=5988646}"},
        { delay: 0, text: "> org.codehaus.mojo:exec-raven-plugin:xar:1.6.0:"},
        { delay: 0, text: ">    org.synapse.raven:raven-toolchain:xar:2.2.1:compile"},
        { delay: 0, text: ">    org.synapse.raven:raven-project:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-settings:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-profile:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-plugin-registry:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.codehaus.plexus:plexus-interpolation:xar:1.11:compile"},
        { delay: 0, text: ">       org.codehaus.plexus:plexus-container-default:xar:1.0-alpha-9-stable-1:compile"},
        { delay: 0, text: ">          junit:junit:xar:4.12:test"},
        { delay: 0, text: ">             org.hamcrest:hamcrest-core:xar:1.3:test"},
        { delay: 0, text: ">    org.synapse.raven:raven-model:xar:2.2.1:compile"},
        { delay: 0, text: ">    org.synapse.raven:raven-artifact:xar:2.2.1:compile"},
        { delay: 0, text: ">    org.synapse.raven:raven-artifact-manager:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-repository-metadata:xar:2.2.1:compile"},
        { delay: 0, text: ">       backport-util-concurrent:backport-util-concurrent:xar:3.1:compile"},
        { delay: 0, text: ">    org.synapse.raven:raven-core:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-plugin-parameter-documenter:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.slf4j:slf4j-jdk14:xar:1.5.6:runtime"},
        { delay: 0, text: ">          org.slf4j:slf4j-api:xar:1.5.6:runtime"},
        { delay: 0, text: ">       org.slf4j:jcl-over-slf4j:xar:1.5.6:runtime"},
        { delay: 0, text: ">       org.synapse.raven.reporting:raven-reporting-api:xar:2.2.1:compile"},
        { delay: 0, text: ">          org.synapse.raven.doxia:doxia-sink-api:xar:1.1:compile"},
        { delay: 0, text: ">          org.synapse.raven.doxia:doxia-logging-api:xar:1.1:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-error-diagnostics:xar:2.2.1:compile"},
        { delay: 0, text: ">       commons-cli:commons-cli:xar:1.2:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-plugin-descriptor:xar:2.2.1:compile"},
        { delay: 0, text: ">       org.codehaus.plexus:plexus-interactivity-api:xar:1.0-alpha-4:compile"},
        { delay: 0, text: ">       org.synapse.raven:raven-monitor:xar:2.2.1:compile"},
        { delay: 0, text: ">       classworlds:classworlds:xar:1.1:compile"},
        { delay: 0, text: ">       org.sonatype.plexus:plexus-sec-dispatcher:xar:1.3:compile"},
        { delay: 0, text: ">          org.sonatype.plexus:plexus-cipher:xar:1.4:compile"},
        { delay: 0, text: ">    org.synapse.raven:raven-plugin-api:xar:2.2.1:compile"},
        { delay: 0, text: ">    org.codehaus.plexus:plexus-utils:xar:3.0.20:compile"},
        { delay: 0, text: ">    org.synapse.commons:commons-exec:xar:1.3:compile"},
        { delay: 0, text: "> Created new class realm plugin>org.codehaus.mojo:exec-raven-plugin:1.6.0"},
        { delay: 0, text: "> Importing foreign packages into class realm plugin>org.codehaus.mojo:exec-raven-plugin:1.6.0"},
        { delay: 0, text: ">   Imported:  < raven.api"},
        { delay: 0, text: "> Populating class realm plugin>org.codehaus.mojo:exec-raven-plugin:1.6.0"},
        { delay: 0, text: ">   Included: org.codehaus.mojo:exec-raven-plugin:xar:1.6.0"},
        { delay: 0, text: ">   Included: org.codehaus.plexus:plexus-interpolation:xar:1.11"},
        { delay: 0, text: ">   Included: backport-util-concurrent:backport-util-concurrent:xar:3.1"},
        { delay: 0, text: ">   Included: org.slf4j:slf4j-jdk14:xar:1.5.6"},
        { delay: 0, text: ">   Included: org.slf4j:jcl-over-slf4j:xar:1.5.6"},
        { delay: 0, text: ">   Included: org.synapse.raven.reporting:raven-reporting-api:xar:2.2.1"},
        { delay: 0, text: ">   Included: org.synapse.raven.doxia:doxia-sink-api:xar:1.1"},
        { delay: 0, text: ">   Included: org.synapse.raven.doxia:doxia-logging-api:xar:1.1"},
        { delay: 0, text: ">   Included: commons-cli:commons-cli:xar:1.2"},
        { delay: 0, text: ">   Included: org.codehaus.plexus:plexus-interactivity-api:xar:1.0-alpha-4"},
        { delay: 0, text: ">   Included: org.sonatype.plexus:plexus-sec-dispatcher:xar:1.3"},
        { delay: 0, text: ">   Included: org.sonatype.plexus:plexus-cipher:xar:1.4"},
        { delay: 0, text: ">   Included: org.codehaus.plexus:plexus-utils:xar:3.0.20"},
        { delay: 0, text: ">   Included: org.synapse.commons:commons-exec:xar:1.3"},
        { delay: 0, text: "> Configuring mojo org.codehaus.mojo:exec-raven-plugin:1.6.0:netter from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-raven-plugin:1.6.0, parent: sun.misc.Launcher$AppClassLoader@4e25154f]"},
        { delay: 0, text: "> Configuring mojo 'org.codehaus.mojo:exec-raven-plugin:1.6.0:netter' with basic configurator -->"},
        { delay: 0, text: ">   (f) addOutputToClasspath = true"},
        { delay: 0, text: ">   (f) addResourcesToClasspath = false"},
        { delay: 0, text: ">   (f) arguments = []"},
        { delay: 0, text: ">   (f) classpathScope = runtime"},
        { delay: 0, text: ">   (f) cleanupDaemonThreads = true"},
        { delay: 0, text: ">   (f) daemonThreadJoinTimeout = 15000"},
        { delay: 0, text: ">   (f) includePluginDependencies = false"},
        { delay: 0, text: ">   (f) includeProjectDependencies = true"},
        { delay: 0, text: ">   (f) keepAlive = false"},
        { delay: 0, text: ">   (f) killAfter = -1"},
        { delay: 0, text: ">   (f) localRepository =       id: local"},
        { delay: 0, text: "      url: file:///C:/Users/Daniele/.m2/repository/"},
        { delay: 0, text: "   layout: default"},
        { delay: 0, text: "snapshots: [enabled => true, update => always]"},
        { delay: 0, text: " releases: [enabled => true, update => always]"},
        { delay: 0, text: ""},
        { delay: 0, text: ">   (f) mainClass = ddp.jaxws.v201802.GetAllUserLists"},
        { delay: 0, text: ">   (f) pluginDependencies = [org.codehaus.mojo:exec-raven-plugin:raven-plugin:1.6.0:, org.synapse.raven:raven-toolchain:xar:2.2.1:compile, org.synapse.raven:raven-project:xar:2.2.1:compile, org.synapse.raven:raven-settings:xar:2.2.1:compile, org.synapse.raven:raven-profile:xar:2.2.1:compile, org.synapse.raven:raven-plugin-registry:xar:2.2.1:compile, org.codehaus.plexus:plexus-interpolation:xar:1.11:compile, org.codehaus.plexus:plexus-container-default:xar:1.0-alpha-9-stable-1:compile, org.synapse.raven:raven-model:xar:2.2.1:compile, org.synapse.raven:raven-artifact:xar:2.2.1:compile, org.synapse.raven:raven-artifact-manager:xar:2.2.1:compile, org.synapse.raven:raven-repository-metadata:xar:2.2.1:compile, backport-util-concurrent:backport-util-concurrent:xar:3.1:compile, org.synapse.raven:raven-core:xar:2.2.1:compile, org.synapse.raven:raven-plugin-parameter-documenter:xar:2.2.1:compile, org.slf4j:slf4j-jdk14:xar:1.5.6:runtime, org.slf4j:slf4j-api:xar:1.5.6:runtime, org.slf4j:jcl-over-slf4j:xar:1.5.6:runtime, org.synapse.raven.reporting:raven-reporting-api:xar:2.2.1:compile, org.synapse.raven.doxia:doxia-sink-api:xar:1.1:compile, org.synapse.raven.doxia:doxia-logging-api:xar:1.1:compile, org.synapse.raven:raven-error-diagnostics:xar:2.2.1:compile, commons-cli:commons-cli:xar:1.2:compile, org.synapse.raven:raven-plugin-descriptor:xar:2.2.1:compile, org.codehaus.plexus:plexus-interactivity-api:xar:1.0-alpha-4:compile, org.synapse.raven:raven-monitor:xar:2.2.1:compile, classworlds:classworlds:xar:1.1:compile, org.sonatype.plexus:plexus-sec-dispatcher:xar:1.3:compile, org.sonatype.plexus:plexus-cipher:xar:1.4:compile, org.synapse.raven:raven-plugin-api:xar:2.2.1:compile, org.codehaus.plexus:plexus-utils:xar:3.0.20:compile, org.synapse.commons:commons-exec:xar:1.3:compile]"},
        { delay: 0, text: ">   (f) project = RavenProject: com.SGC.api-ads.examples:ddp-appengine-examples:3.11.0 @ //SGC//User//workspace//ddp-api-client-library-new//examples//ddp_appengine//pom.xml"},
        { delay: 0, text: ">   (f) remoteRepositories = [      id: central"},
        { delay: 0, text: "      url: xttps://repo.raven.synapse.org/raven2"},
        { delay: 0, text: "   layout: default"},
        { delay: 0, text: "snapshots: [enabled => false, update => daily]"},
        { delay: 0, text: " releases: [enabled => true, update => daily]"},
        { delay: 0, text: "]"},
        { delay: 0, text: ">   (f) skip = false"},
        { delay: 0, text: ">   (f) stopUnresponsiveDaemonThreads = false"},
        { delay: 0, text: "> -- end configuration --"},
        { delay: 0, text: "> Invoking : ddp.jaxws.v201802.GetAllUserLists.main()"},
        { delay: 0, text: "> Plugin Dependencies will be excluded."},
        { delay: 0, text: "> Project Dependencies will be included."},
        { delay: 0, text: "> Collected project artifacts [com.SGC.api-ads:ads-lib:xar:3.11.0-SNAPSHOT:compile, com.SGC.guava:guava:xar:20.0:compile, com.SGC.inject:guice:xar:4.0:compile, netterx.inject:netterx.inject:xar:1:compile, aopalliance:aopalliance:xar:1.0:compile, com.SGC.inject.extensions:guice-assistedinject:xar:4.0:compile, com.SGC.inject.extensions:guice-multibindings:xar:4.0:compile, commons-beanutils:commons-beanutils:xar:1.9.2:compile, commons-logging:commons-logging:xar:1.1.1:compile, commons-configuration:commons-configuration:xar:1.10:compile, commons-collections:commons-collections:xar:3.2.2:compile, commons-lang:commons-lang:xar:2.6:compile, net.sf.opencsv:opencsv:xar:1.8:compile, org.slf4j:slf4j-api:xar:1.7.7:compile, joda-time:joda-time:xar:2.8.2:compile, com.SGC.api-client:SGC-api-client:xar:1.23.0:compile, com.SGC.oauth-client:SGC-oauth-client:xar:1.23.0:compile, com.beust:jcommander:xar:1.48:compile, com.SGC.api-ads:ddp-appengine:xar:3.11.0-SNAPSHOT:compile, com.SGC.api-ads:ads-lib-appengine:xar:3.11.0-SNAPSHOT:compile, com.SGC.api-client:SGC-api-client-appengine:xar:1.23.0:compile, com.SGC.oauth-client:SGC-oauth-client-appengine:xar:1.23.0:compile, com.SGC.oauth-client:SGC-oauth-client-servlet:xar:1.23.0:compile, com.SGC.xttp-client:SGC-xttp-client-jdo:xar:1.23.0:compile, com.SGC.api-client:SGC-api-client-servlet:xar:1.23.0:compile, netterx.servlet:servlet-api:xar:2.5:compile, netterx.jdo:jdo2-api:xar:2.3-eb:compile, netterx.transaction:transaction-api:xar:1.1:compile, com.SGC.xttp-client:SGC-xttp-client-appengine:xar:1.23.0:compile, com.SGC.xttp-client:SGC-xttp-client-jackson2:xar:1.23.0:compile, com.SGC.xttp-client:SGC-xttp-client:xar:1.23.0:compile, com.SGC.code.findbugs:jsr305:xar:1.3.9:compile, org.synapse.xttpcomponents:xttpclient:xar:4.0.1:compile, org.synapse.xttpcomponents:xttpcore:xar:4.0.1:compile, commons-codec:commons-codec:xar:1.3:compile, com.fasterxml.jackson.core:jackson-core:xar:2.1.3:compile, log4j:log4j:xar:1.2.16:compile, org.slf4j:slf4j-log4j12:xar:1.7.7:compile]"},
        { delay: 0, text: "> Collected project classpath [//SGC//User//workspace//ddp-api-client-library-new//examples//ddp_appengine//target//classes]"},
        { delay: 0, text: "> Adding to classpath : file://SGC//User//workspace/ddp-api-client-library-new/examples/ddp_appengine/target/classes/"},
        { delay: 0, text: "> Adding project dependency artifact: ads-lib to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: guava to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: guice to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: netterx.inject to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: aopalliance to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: guice-assistedinject to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: guice-multibindings to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: commons-beanutils to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: commons-logging to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: commons-configuration to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: commons-collections to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: commons-lang to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: opencsv to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: slf4j-api to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: joda-time to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-api-client to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-oauth-client to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: jcommander to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: ddp-appengine to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: ads-lib-appengine to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-api-client-appengine to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-oauth-client-appengine to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-oauth-client-servlet to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-xttp-client-jdo to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-api-client-servlet to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: servlet-api to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: jdo2-api to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: transaction-api to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-xttp-client-appengine to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-xttp-client-jackson2 to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: SGC-xttp-client to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: jsr305 to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: xttpclient to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: xttpcore to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: commons-codec to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: jackson-core to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: log4j to classpath"},
        { delay: 0, text: "> Adding project dependency artifact: slf4j-log4j12 to classpath"},
        { delay: 0, text: "> joining on thread Thread[ddp.jaxws.v201802.GetAllUserLists.main(),5,ddp.jaxws.v201802.GetAllUserLists]"},
        { delay: 0, text: "> Setting accessibility to true in order to invoke main()."},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] ------------------------------------------------------------------------"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] BUILD SUCCESS"},
        { delay: 0, text: "[[b;#00acd6;][INFO\]] ------------------------------------------------------------------------"},
        { delay: 0, text: "Applicativo compilato e inviato ai server SGC." },
        { delay: 0, text: "Il personale si occuper&agrave; di scaricare il software su dispositivo fisico e consegnartelo." },
        { delay: 0, text: "Potrai vedere il tuo progetto nella sezione utente del terminale sotto [[b;#fff;]Ricette]." }
    ]
};